let a=1000;
let b=20;
let c=30;
let d="manohar"
let e="boddolla"
let f="true"
let g="false"
let h;
console.log (a/b)
console.log (a/c)
console.log (a/e)
console.log (a/f)
console.log (a/f)
console.log (a/g)
console.log (a/h)
