let employees = [{"id":1,"name":"Melli","email":"mfoxen0@google.co.jp","gender":"Non-binary"},
{"id":2,"name":"Isobel","email":"iveeler1@cnbc.com","gender":"Female"},
{"id":3,"name":"Shelley","email":"smcmaster2@people.com.cn","gender":"Male"},
{"id":4,"name":"Edin","email":"eballach3@ucsd.edu","gender":"Female"},
{"id":5,"name":"Jamison","email":"jreef4@addthis.com","gender":"Male"},
{"id":6,"name":"Freeman","email":"ffranchyonok5@paginegialle.it","gender":"Male"},
{"id":7,"name":"Curt","email":"cbengtsen6@ameblo.jp","gender":"Bigender"},
{"id":8,"name":"Albina","email":"aaggis7@techcrunch.com","gender":"Female"},
{"id":9,"name":"Lodovico","email":"lgunner8@soundcloud.com","gender":"Male"},
{"id":10,"name":"Amalle","email":"abuttle9@yahoo.com","gender":"Female"},
{"id":11,"name":"Tabby","email":"tduligalla@phpbb.com","gender":"Male"},
{"id":12,"name":"Saundra","email":"stredgerb@opera.com","gender":"Male"},
{"id":13,"name":"Francene","email":"fhaffordc@dell.com","gender":"Female"},
{"id":14,"name":"Shanta","email":"sbaudinsd@dyndns.org","gender":"Genderqueer"},
{"id":15,"name":"Theadora","email":"tkarpmane@t.co","gender":"Female"},
{"id":16,"name":"Kiley","email":"ktrussellf@elpais.com","gender":"Female"},
{"id":17,"name":"Glyn","email":"gloughg@ow.ly","gender":"Polygender"},
{"id":18,"name":"Artair","email":"ablydenh@noaa.gov","gender":"Male"},
{"id":19,"name":"Claiborn","email":"chairi@hao123.com","gender":"Male"},
{"id":20,"name":"Phoebe","email":"porthj@mlb.com","gender":"Female"},
{"id":21,"name":"Irv","email":"imatthewsk@merriam-webster.com","gender":"Male"},
{"id":22,"name":"Dorelia","email":"dbeartl@barnesandnoble.com","gender":"Female"},
{"id":23,"name":"Guthrie","email":"gmcmeekinm@apple.com","gender":"Male"},
{"id":24,"name":"Wiley","email":"wsaurinn@ucoz.com","gender":"Male"},
{"id":25,"name":"Vladamir","email":"vpotzoldo@ted.com","gender":"Male"},
{"id":26,"name":"Lenee","email":"lrettiep@surveymonkey.com","gender":"Non-binary"},
{"id":27,"name":"Celestina","email":"cvigarq@skyrock.com","gender":"Female"},
{"id":28,"name":"Emily","email":"emeaderr@soup.io","gender":"Female"},
{"id":29,"name":"Juliana","email":"jstreetleys@go.com","gender":"Female"},
{"id":30,"name":"Obie","email":"oblackstont@psu.edu","gender":"Male"},
{"id":31,"name":"Josephina","email":"jdenekampu@umn.edu","gender":"Female"},
{"id":32,"name":"Zelig","email":"zscolesv@photobucket.com","gender":"Male"},
{"id":33,"name":"Marjy","email":"mbutnerw@constantcontact.com","gender":"Female"},
{"id":34,"name":"Helen-elizabeth","email":"hgockelenx@miitbeian.gov.cn","gender":"Female"},
{"id":35,"name":"Jacinda","email":"jgutersony@stumbleupon.com","gender":"Female"},
{"id":36,"name":"Barrie","email":"bcanetz@hubpages.com","gender":"Polygender"},
{"id":37,"name":"Lynn","email":"lbrumwell10@skyrock.com","gender":"Male"},
{"id":38,"name":"Franklin","email":"fdeglanville11@shareasale.com","gender":"Male"},
{"id":39,"name":"Adela","email":"amcvey12@cnbc.com","gender":"Female"},
{"id":40,"name":"Dory","email":"dgeorge13@domainmarket.com","gender":"Genderfluid"},
{"id":41,"name":"Lindsy","email":"lfaragan14@quantcast.com","gender":"Female"},
{"id":42,"name":"Giles","email":"gflaxon15@wiley.com","gender":"Male"},
{"id":43,"name":"Vi","email":"vbarson16@comcast.net","gender":"Female"},
{"id":44,"name":"Geri","email":"gcastagneri17@godaddy.com","gender":"Male"},
{"id":45,"name":"Aurea","email":"atreadway18@tinyurl.com","gender":"Female"},
{"id":46,"name":"Huntley","email":"hthorneywork19@webmd.com","gender":"Non-binary"},
{"id":47,"name":"Shep","email":"slearned1a@timesonline.co.uk","gender":"Male"},
{"id":48,"name":"Parnell","email":"probathon1b@hp.com","gender":"Male"},
{"id":49,"name":"Timoteo","email":"tprudham1c@sbwire.com","gender":"Polygender"},
{"id":50,"name":"Hussein","email":"hygoe1d@ftc.gov","gender":"Male"},
{"id":51,"name":"Vikky","email":"vsaltrese1e@mashable.com","gender":"Female"},
{"id":52,"name":"Malva","email":"mmasdon1f@mapquest.com","gender":"Female"},
{"id":53,"name":"Loutitia","email":"lclancy1g@vinaora.com","gender":"Female"},
{"id":54,"name":"Constantia","email":"clawlings1h@nasa.gov","gender":"Female"},
{"id":55,"name":"Felicdad","email":"fpallas1i@ow.ly","gender":"Female"},
{"id":56,"name":"Sasha","email":"skent1j@yandex.ru","gender":"Male"},
{"id":57,"name":"Emma","email":"elafay1k@upenn.edu","gender":"Female"},
{"id":58,"name":"Goraud","email":"gginglell1l@cdc.gov","gender":"Male"},
{"id":59,"name":"Farica","email":"fdeeprose1m@time.com","gender":"Female"},
{"id":60,"name":"Amble","email":"agrube1n@hostgator.com","gender":"Male"},
{"id":61,"name":"Emelda","email":"ecourtes1o@fema.gov","gender":"Female"},
{"id":62,"name":"Corenda","email":"cbrevitt1p@google.de","gender":"Agender"},
{"id":63,"name":"Deedee","email":"ddarwent1q@ocn.ne.jp","gender":"Female"},
{"id":64,"name":"Boot","email":"bmonni1r@businessweek.com","gender":"Male"},
{"id":65,"name":"Patrica","email":"phurles1s@pinterest.com","gender":"Female"},
{"id":66,"name":"Meghan","email":"myanez1t@nyu.edu","gender":"Female"},
{"id":67,"name":"Nina","email":"nnevinson1u@ow.ly","gender":"Female"},
{"id":68,"name":"Neils","email":"nfloweth1v@prlog.org","gender":"Male"},
{"id":69,"name":"Adrienne","email":"aoliverpaull1w@tinypic.com","gender":"Female"},
{"id":70,"name":"Dave","email":"doty1x@google.com.br","gender":"Male"},
{"id":71,"name":"Herbie","email":"hdamerell1y@networksolutions.com","gender":"Male"},
{"id":72,"name":"Tris","email":"tpendlebury1z@hugedomains.com","gender":"Male"},
{"id":73,"name":"Bobette","email":"bcotter20@1und1.de","gender":"Non-binary"},
{"id":74,"name":"Isa","email":"ifynan21@zdnet.com","gender":"Female"},
{"id":75,"name":"Jess","email":"jjayume22@google.com","gender":"Female"},
{"id":76,"name":"Blondell","email":"bodoireidh23@google.com","gender":"Female"},
{"id":77,"name":"Winnifred","email":"wkira24@usa.gov","gender":"Female"},
{"id":78,"name":"Alric","email":"amatashkin25@blinklist.com","gender":"Male"},
{"id":79,"name":"Bertram","email":"bkennham26@pcworld.com","gender":"Male"},
{"id":80,"name":"Ki","email":"kkitcatt27@a8.net","gender":"Female"},
{"id":81,"name":"Selie","email":"sgainseford28@bbc.co.uk","gender":"Female"},
{"id":82,"name":"Felizio","email":"fgrgic29@odnoklassniki.ru","gender":"Male"},
{"id":83,"name":"Alexine","email":"astuckey2a@webeden.co.uk","gender":"Female"},
{"id":84,"name":"Bryce","email":"bcrowley2b@issuu.com","gender":"Male"},
{"id":85,"name":"Ursuline","email":"ugley2c@gov.uk","gender":"Female"},
{"id":86,"name":"Van","email":"vmaccahey2d@sina.com.cn","gender":"Male"},
{"id":87,"name":"Robinetta","email":"rshilstone2e@de.vu","gender":"Female"},
{"id":88,"name":"Quincey","email":"qrhelton2f@bandcamp.com","gender":"Male"},
{"id":89,"name":"Anthe","email":"abrashaw2g@examiner.com","gender":"Female"},
{"id":90,"name":"Arlie","email":"aclamo2h@dyndns.org","gender":"Female"},
{"id":91,"name":"Devondra","email":"dsemour2i@theguardian.com","gender":"Female"},
{"id":92,"name":"Hamlen","email":"hvertey2j@bluehost.com","gender":"Male"},
{"id":93,"name":"Gabriele","email":"gbredee2k@fotki.com","gender":"Male"},
{"id":94,"name":"Allys","email":"ahuckel2l@cdc.gov","gender":"Female"},
{"id":95,"name":"Matty","email":"mpile2m@howstuffworks.com","gender":"Male"},
{"id":96,"name":"Myra","email":"mbuntin2n@shinystat.com","gender":"Female"},
{"id":97,"name":"Sander","email":"sledbetter2o@wunderground.com","gender":"Male"},
{"id":98,"name":"Sherye","email":"scrowcher2p@etsy.com","gender":"Female"},
{"id":99,"name":"Rachael","email":"rbuglass2q@amazonaws.com","gender":"Female"},
{"id":100,"name":"Chev","email":"csliman2r@rambler.ru","gender":"Male"}]

function love(){
    let rows = ""
for (employee of employees){
    rows = rows+ ` <tr>
                        <td> ${employee.id}</td>
                        <td> ${employee.name}</td>
                        <td> ${employee.email}</td>
                        <td> ${employee.gender}</td>
                    </tr>
    `
}
document.getElementById("table").innerHTML=rows
}

